### ISSUE TITLE
Unexpected behaviour on 404

### ISSUE THREAD

**Issue by spekulatius** [dljoseph/silverstripe-maintenance-mode#13]
If the maintenance mode is on and I request a URL which doesn't exist (404) I get a blank page. I would expect the maintenance page to show up.

**Comment by dljoseph** [comment]
I'll look into this.  Out of interest, which version of the framework are you using, 3.1.x or 3.2 rc2 ?

**Comment by spekulatius** [comment]
It is a old project based on 3.1.4 - needs to updated. I'll verify if this happens on 3.1.15 as well...

**Comment by dljoseph** [comment]
I've checked...definitely an issue.  Thanks for reporting this.  I'll investigate.

**Comment by spekulatius** [comment]
Okay, thanks for checking and confirming this so quickly
