### ISSUE TITLE
Extension vulnerable to IP spoofing, should use framework to retrieve IP.

### ISSUE THREAD

**Issue by patricknelson** [dljoseph/silverstripe-maintenance-mode#15]
While possibly minor, the extension should use the existing method for retrieving IP address here: https://github.com/silverstripe/silverstripe-framework/blob/3/control/HTTPRequest.php#L657

This is because it goes through the necessary security checks to ensure that the relevant IP HTTP request headers are from a trusted proxy first before accepting them.

**Comment by dljoseph** [comment]
Good catch.... I'll submit a patch in a few moments.

**Comment by patricknelson** [comment]
I'm already on it

**Comment by dljoseph** [comment]
lol - ok cool... over to you :)

**Comment by patricknelson** [comment]
It's effectively a one line change (except for the lines being deleted) :+1: 

It just stood out to me since I had to deal with this already with 2-3 different interstitial proxies between clients and my site (client -> Akamai -> Load Balancer -> 1 of several servers).

**Comment by dljoseph** [comment]
Top man!  Merged.  New release v1.0.1 created.
