### ISSUE TITLE
Automatically enter maintenance mode when running a build

### ISSUE THREAD

**Issue by Firesphere** [dljoseph/silverstripe-maintenance-mode#17]
It would be cool, if a site automatically went into maintenance-mode, when a dev/build is run. And only get out of the maintenance-mode when the build (and possibly flush) was successful. If unsuccessful, send an e-mail to the developer.

I know, it's not an easy thing to implement, but would be cool :)

**Comment by Firesphere** [comment]
Since my e-mailaddress seems to be marked as "Spam" often by GMail, please check your spam-folder for an e-mail from me ;)

**Comment by dljoseph** [comment]
I've seen your develop branch.  I like the solution :)

**Comment by Firesphere** [comment]
It needs some smoothing, like when the module is installed after the initial database has been build, it'll probably break, but I'll get that working and then create a pull-request :)

**Comment by mattrayner** [comment]
@Firesphere Any news on this? I'd love to see your solution 👍

**Comment by Firesphere** [comment]
Quick summary? I moved my whole life to New Zealand from the Netherlands.
Sorry, I'm already glad I could update some other websites ;)
