### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by spekulatius** [dljoseph/silverstripe-maintenance-mode#7]
It would be great if the versioning would align with SilverStripe common practice of using semver. More information about this can be found here: http://semver.org/

**Comment by dljoseph** [comment]
Yeah ....that's the plan.  This module was supposed to be marked as a pre-release/beta version.  I'll iron out the remaining issues (time permitting) and release version 1.0.0 within the next few weeks.

**Comment by spekulatius** [comment]
Cool, that would be great!

**Comment by dljoseph** [comment]
Released version 1.0.0.  Adopted Semantic Versioning to be applied from hence forth.

**Comment by spekulatius** [comment]
Great! Thanks man!
